### ISSUE TITLE
Consider Cleaning up Tests with unittest_data

### ISSUE THREAD

**Issue by wbond** [wbond/package_control_channel#3915]
I just wrote https://github.com/wbond/unittest_data for data-provider driven tests.

While not 100% different from the current approach since it still generates test methods, it may produce code that is easier to follow.

**Comment by FichteFoll** [comment]
@wbond is this still something you intend to look at?

**Comment by wbond** [comment]
Yes, I would still like to look into it, however I still haven't finished those projects yet.

I think I'm about on a 9-month yak shaving expedition. :smile:

**Comment by braver** [comment]
This is by now a really old idea. My personal experience is that 8 years ago I didn't have ideas that were as good as ones I've been having recently. 

For instance, IMO, tests here should focus on having the repository files match a schema. We're not responsible for the quality of the packages themselves. Taking on that responsibility even in a limited way has burned out all previous package reviewers. We do some checks, and that's fine.

So what kind of unit tests does what's essentially just a JSON file need? A schema check, maybe a formatter. Maybe you could typo-check labels if you find that really important.

The entire world around running such tests has changed since this issue was initially filed. Let's close this for now until we A. feel a need for something and B. find that need important enough to actually do something about with (at that point) current technology.
