### ISSUE TITLE
How to Exclude Files from Package Control Install?

### ISSUE THREAD

**Issue by benmarten** [wbond/package_control_channel#4328]
We recently added: https://github.com/ColibriApps/MonokaiJsonPlus to Package Control.

An issue got reported (https://github.com/ColibriApps/MonokaiJsonPlus/issues/2) where I saw that package control seems to install all files from our repository. Is there any way to configure what files are installed during package control install?

**Comment by wbond** [comment]
There is no way to "filter" files in your repo via Package Control. That would be a waste since the files would all be downloaded (GitHub zip downloads contain everything in a tag), but then deleted locally.

However, there are ways to not install everything from your development repo:

1. Manually create a `.sublime-package` file using Package Control. This probably isn't what you want.
2. Create a branch that pulls in changes from `master` and create the release tags from this branch.
