### ISSUE TITLE
Why package publishing takes too long?

### ISSUE THREAD

**Issue by lnmunhoz** [wbond/package_control_channel#5376]
Why we should run tests to validate the JSON if this PR process takes more than a week? How can we make this more faster?

**Comment by FichteFoll** [comment]
Because I was on vacation and am the only person to review pull request in the past two years. I do this in my free time, by the way.

The process is generally sub-optimal, but there are no resources to work on a more streamlined and automated process at this moment.

**Comment by lnmunhoz** [comment]
You don't want some help?

**Comment by FichteFoll** [comment]
Oh, I do.

I took the time to write down our (my) guidelines for reviewing pull requests here: https://github.com/wbond/package_control_channel/wiki/Pull-Request-Review-Guidelines

After you made yourself familiar with it (and maybe followed some of the requests for a bit) and still want to do it, I imagine @wbond would add you as a collaborator so that you can help balance the load.
