### ISSUE TITLE
Add package but exclude test/test data folder

### ISSUE THREAD

**Issue by stoivo** [wbond/package_control_channel#5942]
Hello

I have a question. We at GitSavvy would like to write some tests but we wouldn't like for everyone installing our to download our test and test data? Is this possible to specify this in `repository/g.json`?

**Comment by FichteFoll** [comment]
No.

You can either:

1. Pack your `.sublime-package` file manually and reference it in a custom `repositories.json` file that you reference in this repo's `channels.json` file.
2. Host development and release versions in separate branches (or repositories). Only tags will be fetched by Package Control and you `master` branch can contain the development version with tests.
3. Ship the tests anyway.

**Comment by stoivo** [comment]
Thanks for telling about the options.

Would it be interesting to add an option  in g.json that would look like
```json
		{
			"name": "GitSavvy",
			"details": "https://github.com/divmain/GitSavvy",
			"labels": [
				"git",
				"dashboard",
				"inline",
				"stage",
				"patch"
			],
			"readme": "https://raw.githubusercontent.com/divmain/GitSavvy/master/README.md",
			"author": "divmain",
			"releases": [
				{
					"sublime_text": ">=3000",
					"tags": true,
					"exclude": ['test/', test_data/]
				}
			]
		},
``` 

If so, maybe I could implement that.

**Comment by FichteFoll** [comment]
It would be possible to remove folders from the downloaded archive, but regardless of whether they would be deleted or not, since Package Control downloads the entire zip archive of the tag, they would have to be downloaded either way. Deleting it afterwards might not consume disk space but still consumes bandwidth.

Imo it's not worth to add this functionality, but this would be a suggestion for https://github.com/wbond/package_control.
