### ISSUE TITLE
Running pull request tests pre-submit

### ISSUE THREAD

**Issue by mphstudios** [wbond/package_control_channel#6433]
ChannelRepositoryTools do not run the same automated tests as the packagecontrol-bot. Is there documentation on how to run the post pull request tests on the package repository in order to resolve issues before submitting the pull request and watching the tests fail?

**Comment by FichteFoll** [comment]
Automated tests are run automatically when a new commit is pushed (and when a PR is re-opend, I think). They can also be triggered manually, however @wbond intentionally didn't publicise the method to doing so in order to prevent people from flooding the endpoint. I'll leave this up to him to respond.

**Comment by wbond** [comment]
Yes, my plan is to make it possible to trigger in the future via channel repository tools, however for now you can go to https://packagecontrol.io/test_repo and paste in the JSON object for your repository to test it.

Part of the issue is not having time to work on it right now since I am knee deep getting ST 3.0 out the door. Part of the issue is having to try and automate `git` commands on the user's machine and writing all of the documentation to help people get git on their PATH and junk like that.

**Comment by braver** [comment]
ChannelRepositoryTools is 8 years old now, I’m not sure anybody really uses it for anything.

Adding entries to package control is easy enough. Just create the PR and let the bot do its thing. Hundreds of packages are successfully added each year without any local tooling.

The package tests can already be run locally as mentioned in this thread.

So, let’s say “won’t fix” (which is has been implicitly for 5 years already) and work on more pressing issues.
