### ISSUE TITLE
Why is my plugin installed as a sublime-package in the "Installed Packages" directory?

### ISSUE THREAD

**Issue by lintingbin2009** [wbond/package_control_channel#6556]
Why is my plugin installed as a sublime-package in the "Installed Packages" directory? I want to install my package as a folder in the "Packages" directory(like jedi, SublimeLinter). Now my plugin can not work properly, can not find his dependent library, how do i do this change? My plugin is “Erl-AutoCompletion“.

**Comment by OdatNurd** [comment]
The last part of step 5 in the Submitting a Package portion of the [documentation on Submitting a Package](https://packagecontrol.io/docs/submitting_a_package) says:

> If including executables or shared libraries, add a .no-sublime-package file. Adding this file to the root of your repository will prevent Package Control from keeping your package packed as a .sublime-package file in ST3.

If you add such a file to your package, when PackageControl installs it it will leave it unpacked instead of packing it up, which it does by default.

**Comment by lintingbin2009** [comment]
Thanks for your answer.
