### ISSUE TITLE
Add my fork of the BufferScroll to package control

### ISSUE THREAD

**Issue by evandrocoan** [wbond/package_control_channel#6907]
@titoBouzout I have forked 2 of your packages I daily use and fixed some stuff which was not working. These are the packages:

1. https://github.com/evandrocoan/BufferScroll
1. https://github.com/evandrocoan/WordCount

Currently the `WordCount` package is already on Package Control from the fork of @philipbelesky:
1. https://github.com/philipbelesky/WordCount

But there are no new commits on it. @philipbelesky, can I add my fork in-place of yours?

If you prefer I can add both under a different name like `View Settings Save` and `View Status`.

**Comment by philipbelesky** [comment]
@evandrocoan my fork was just for the purposes of publishing to Package Control so I wasn't planning on doing anything more than mirror @titoBouzout 's repo. I'm a bit apprehensive about swapping out which repo is linked to as `WordCount` on package control; to my mind tito has claim to that name given they initially published those packages. Ideally your PR would be merged but if not I think they should make the call as to which package is listed as `WordCount`

**Comment by titoBouzout** [comment]
relevant for word count https://github.com/titoBouzout/WordCount/pull/56

Maybe you can add these using a different name, as gonna be confusing if you change stuff and there's two packages with the same name behaving differently. gl

**Comment by evandrocoan** [comment]
Thanks for the response. I could then:

1. Keep the name and push a major release for both packages announcing breaking changes.
1. Add them both with new names.

@FichteFoll, which one of these options would accept merging?

**Comment by FichteFoll** [comment]
Thanks for the references, but I do not have the capacity to review them.

If @titoBouzout thinks the changes are fine and can agree to you taking over the old packages, then let's do that. This is largely preferrable because all existing users of the packages will benefit from continued maintenance and fixed bugs. Less used features that were potentially removed could be communicated through update messages.
I suggest to provide a summary of your changs for @titoBouzout to review (you tried in https://github.com/titoBouzout/WordCount/pull/56, but try to be more concise without leaving out things. Then you can go on about the reasons for the changes in a different sections.

If this somehow doesn't work out, option 2 is also fine.

**Comment by braver** [comment]
@evandrocoan Sorry, this has been sitting for a while. By now both original packages are really ancient. 

Can you make major releases for both, add message about anything that might break for existing users, and then create PRs to replace the existing WordCount package? 

BufferScroll currently isn't listed, so you can choose a new name there, or take the old one. We can then give everyone 2 weeks to object, but I expect we can then move forward and add your versions of these packages to the channel.

I'll close this issue, we can continue in the PRs.
