### ISSUE TITLE
New pull requests not being reviewed or submitted. Project alive?

### ISSUE THREAD

**Issue by whatnickcodes** [wbond/package_control_channel#7029]
Appreciate all team's hard work, anyway to get reviewed? Just been waiting about a month + now.

Anyway to somehow jumpstart this? Or, maybe put a big fat flag for developers and others that the process is extremely slowed / partly dead and abandoned.

https://github.com/wbond/package_control_channel/pull/6974

**Comment by whatnickcodes** [comment]
Also understand if you guys aren't approving new themes because of clutter or something. Just can't get update or find any info regarding it.

Ideas regarding capacity and approval process to keep this alive overtime:

- **Heads Up**: Maybe on the website or in the docs put a huge warning on the website to developers about the approval process being slowed.

- **Package Control (themes/color schemes)*: Maybe separate out themes / color schemes from the normal package_control_channel that is a bit more automated and messy. Auto removes itself if no downloads or update every 3-6 months or something.

Thanks again. Just my thoughts and trying to get my stupid theme approved.

**Comment by FichteFoll** [comment]
The workload for reviewing packages is huge, I am practically the only person reviewing and I have *just* been on vacation for 12 days.

It would help if more people would chime in and point out flaws in packages and make them aware of proper conventions, but unfortunately this requires quite a bit of knowledge about the package infrastructure itself that not many people have - and those that do would probably rather spend their time otherwise.

I'll try to get back to a minimum wait time of 14 days over the next week, but I'm not promising anything. I know it's frustrating not to hear back for a month's time, but it *is* a demanding process (and one that I do voluntarily because I care about the quality of our package ecosystem).

I treat every type of package the same, so I doubt I would push themes forward in the queue even when they are easier to review. Ideally people would only have to wait a few days for a review anyway, but it'll take a while until we're back at that pace.

FYI, if your pull request hasn't receive a comment from me (or wbond), it just hasn't been reviewed yet.

**Comment by whatnickcodes** [comment]
A full 12 days of break sounds amazing... I hope that was a blast.

Thanks for info.

Honestly just super bummed it hasn't gone through even though it's a stupid lazy theme. I thought it was more automated but this makes a lot of sense what you are saying and I respect your work load / schedule and diligence on making sure things are done right.

I don't think people mind waiting super long periods (14 days, 1 month, multiple months), maybe give a heads up to set expectations in the docs or wiki. Totally reasonable and people will understand. If you see this being another month plus out, I do not mind waiting and really just want to know.

Beyond that, thanks for response. I donated $50 a couple of weeks ago to the project because I understand how taxing this all can be (help support a few github things myself that always are very behind on issues). I hope wbond split it with you. If he did not, please give me your PayPal so I can directly support the time put forth on this project.

**Comment by FichteFoll** [comment]
Thanks for your understanding words. I'll probabaly update the PR template to include a mention about the increased wait time so that package authors don't get frustrated over longer wait periods.

Will has sent me some money a couple years ago through gratipay ("gittip" back then), but hasn't for a while. I just created a page on ko-fi.com for occasions like this, so feel free to use it: https://ko-fi.com/fichtefoll

PS: Just to clarify, that won't make your package get reviewed faster because I strictly operate on a first-come first-serve basis with notable exceptions for security- or privacy-related issues. Though, I suppose you suspected that already.

**Comment by whatnickcodes** [comment]
Awesome regarding adding the warning.

Awesome about ko-fi. Just contributed.

Awesome about clarifying. No special treatment, when you get to it you get to it. Just want to let you know are out there who appreciate what you have done and are doing. No idea how many thanks I can give for improving my dev life. Anything to help keep this motivated and alive.

Cheers!
