### ISSUE TITLE
Add [print]

### ISSUE THREAD

**Issue by jrappen** [wbond/package_control_channel#7833]
## https://github.com/jrappen/sublime-print

> Please see repo for code.

---

I'll add the following code to my channel file once approved at:

https://github.com/jrappen/sublime-packages

```diff
+           "name": "print",
+           "author": "Johannes Rappen (jrappen)",
+           "details": "https://github.com/jrappen/sublime-print",
+           "donate": "https://paypal.me/jrappen",
+           "labels":
+           [
+               "print",
+               "printing",
+               "html-preview"
+           ],
+           "releases":
+           [
+               {
+                   "sublime_text": ">=4065",
+                   "tags": true
+               }
+           ]
+       },
+       {
```

**Comment by FichteFoll** [comment]
Why do you even keep the separate repo? (I mean, I'm subject to that as well, but that's primarily because I've been too lazy to migrate.)

Regardless, the package's name is more than misleading. It shows a rendered preview in either minihtml or the browser using `mdpopups`. There is no actual printing involved. Besides, isn't this exactly what https://packagecontrol.io/packages/ExportHtml is doing?

**Comment by jrappen** [comment]
> Why do you even keep the separate repo? (I mean, I'm subject to that as well, but that's primarily because I've been too lazy to migrate.)

I mainly keep the private packages repo to frequently update the requirements.

> Regardless, the package's name is more than misleading. It shows a rendered preview in either minihtml or the browser using `mdpopups`. There is no actual printing involved. Besides, isn't this exactly what [packagecontrol.io/packages/ExportHtml](https://packagecontrol.io/packages/ExportHtml) is doing?

Fair point.
