### ISSUE TITLE
Is it possible to add message pack?

### ISSUE THREAD

**Issue by TACIXAT** [wbond/package_control_channel#7851]
https://github.com/msgpack/msgpack-python

If I were to do this, do I need to create a mirror of it? Any advice on how to go about this?

Thanks!

**Comment by FichteFoll** [comment]
Yes, you need to mirror it. If the pure-python is fine, you can structure it similarly to the [`requests` dependency](https://github.com/packagecontrol/requests).

If you want to include binaries, things will get more complicated since you need to either compile them or use pre-compiled binaries from pypi wheels, for example, which usually only exist for Windows. [pywinpty](https://github.com/packagecontrol/pywinpty) does this, for example.

See also the [documentation](https://packagecontrol.io/docs/dependencies).

**Comment by FichteFoll** [comment]
Actually, [`pyzmq`](https://github.com/packagecontrol/pyzmq) is an even better example, since it automatically builds the binaries using github actions.
