### ISSUE TITLE
Moved and disappeared packages

### ISSUE THREAD

**Issue by npanuhin** [wbond/package_control_channel#7869]
Looking through the list of packages, I found those that (for whatever reason) were [moved](https://gist.github.com/npanuhin/07728bdd8c83eaacfaa055908e262a24) or [even deleted](https://gist.github.com/npanuhin/7dddfc14094681326a75f2f6504191c9). Now I wonder what to do with them:

Firstly, I think that the links of packages that have been moved should be replaced with new ones. This will not affect their performance. On the contrary, it will have a good effect on the behavior of Package Control (obvious reasons).

But with deleted packages, this is not so simple. I suggest the following:
It is clear that if the package is unavailable for several months, then most likely it can be removed. Fortunately, this is very simple to determine since there is a "Last Seen" field on the page of each package, which under normal conditions never exceeds 3-4 hours. This is a one-time solution because it uses the network to receive data, but it is better than nothing.

I would appreciate if @wbond and @FichteFoll express their opinion on this.

**Comment by FichteFoll** [comment]
Thanks for collecting these lists. The moved packages are an easy change that I can merge easily after a quick verification. If you could share the script you used to fetch these, it would be easier for me as I wouldn't have to make one myself. Otherwise I'll write a quick curl wrapper.

For the deleted packages, I have not entirely decided on how to handle them. Generally, if they have been missing for a long time, there is no reason to keep listing the package, but occasionally authors just weren't aware that their repositories has gone missing. 

I suggest we notify all package authors that their package has gone missing through a Github issue and proceed with removing them after they haven't reacted in a month or so. There [may be a limit to how many users you can mention in an issue or comment](https://github.com/tqdm/tqdm/issues/887#issuecomment-594896713), so we'd need to consider that.

The site knows how to handle removed packages, becaue it removes them from the search index while keeping up the direct URLs to the package and adding a "Removed" marker, so I'm not worried about that.

Would like to hear from @wbond before moving forward.

**Comment by braver** [comment]
> I suggest we notify all package authors that their package has gone missing through a Github issue and proceed with removing them after they haven't reacted in a month or so.

That is a lot of work. Realistically we’re never going to it, especially not regularly. 

Furthermore, there is a point to be made for keeping packages the repository regardless of their actual availability. A name that was once taken for one package should not at a later time become available for an entirely different package. Note that users will have that deleted package installed and potentially at a later time replaced. By keeping the entry in the repository we guarantee that a package is not replaced without a review of one of the maintainers. As such, yes, there actually _is_ a reason to keep listing packages that are no longer available.

Besides, there is no problem to solve: the application already handles “missing” packages correctly.

**Comment by FichteFoll** [comment]
The packagecontrol.io site currently has some problems with packages not showing up as missing even though they clearly are, but that's a problem on that front and we already have an issue for it.
