### ISSUE TITLE
I want to release a new package as a successor to a package that has not been maintained for several years

### ISSUE THREAD

**Issue by thep0y** [wbond/package_control_channel#8605]
The author of the [old package](https://github.com/adambullmer/sublime_docblockr_python), although still active, has not maintained this package for 4 years. The availability of this package has become an issue over time.

I want to release a [new package](https://github.com/thep0y/python-docblockr) based on this package, fix some fatal bugs, and add some new features.

The new package is only released for ST4.

Is this allowed?

**Comment by idleberg** [comment]
Some thoughts on this practice: https://github.com/wbond/package_control_channel/issues/8595

**Comment by FichteFoll** [comment]
In general, yes, we do allow package takeovers per the process that is discussed in #8595 (albeit without much input so far because it's a rather significant discussion and potential change to have).

As for your case in particular, the package does indeed seem to be abandoned, seeing how it's been broken on ST4 with a trivial fix available for over a year now: https://github.com/adambullmer/sublime_docblockr_python/issues/49. Our usual procedure can also be viewed [in the review guidelines](https://github.com/wbond/package_control_channel/wiki#reviewing-a-package-change), but in general takeovers are allowed if the previous maintainer agrees or does not reply within ~2 weeks to a takeover request.
